name: Sticky Note App
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push: 
      branches:
        - workflow/multistep
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test step..."
