name: Hello World
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Step 2"
      - run: echo "Hello World!"
