name: Build sticky-note-app
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ "workflow/multistep" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: frontend/notes-app/.
          push: true
          tags: sqlviren/sticky-note-frontend:latest
      
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: backend/.
          push: true
          tags: sqlviren/sticky-note-backend:latest
          